'use client';import {useMemo,useState} from 'react';import type {TravelDay} from '../types/travel';
const stars=(n:number)=>'★'.repeat(n)+'☆'.repeat(5-n);
function Photo({src,alt}:{src:string;alt:string}){return src?<img className="photo" src={src} alt={alt} loading="lazy"/>:<div className="placeholder">真人穿搭攝影待上傳</div>}
export default function TravelApp({days}:{days:TravelDay[]}){const chapters=[...new Set(days.map(d=>d.chapter))];const [chapter,setChapter]=useState(chapters[0]||'');const visible=useMemo(()=>days.filter(d=>d.chapter===chapter),[days,chapter]);const [selected,setSelected]=useState('');const day=visible.find(d=>d.date===selected)||visible[0]||days[0];return <main>
<section className="hero"><div><span>2026.08.13 — 08.28</span><h1>CANADA<br/>2026</h1><p>17 天 · 4 種氣候篇章 · 一套衣櫥</p></div></section>
<section id="today"><p className="eyebrow">今天穿什麼？</p><h2>{day?.title}</h2><div className="tabs">{chapters.map(c=><button className={c===chapter?'active':''} onClick={()=>{setChapter(c);setSelected('')}} key={c}>{c}</button>)}</div><div className="subtabs">{visible.map(d=><button className={d.date===day?.date?'active':''} onClick={()=>setSelected(d.date)} key={d.date}>{d.date.replace('2026/','')}</button>)}</div>{day&&<Day day={day}/>}</section>
<section id="levels"><p className="eyebrow">穿搭厚度</p><h2>五級分層系統</h2><div className="levelgrid">{['20°C 以上｜夏裝','15–20°C｜薄外層','10–15°C｜刷毛＋防風','5–10°C｜底層＋中層＋羽絨','0–5°C／高山強風｜羽絨＋Shell'].map((x,i)=><div className="level" key={x}><b>LEVEL {i+1}</b><strong>{stars(i+1)}</strong><p>{x}</p></div>)}</div></section>
<nav><a href="#today">今天</a><a href="#today">地點</a><a href="#levels">厚度</a><a href="#packing">行李</a></nav></main>}
function Day({day}:{day:TravelDay}){return <article className="day"><header><div><span>{day.date} · {day.chapter}</span><div className="temp">{day.dayTemp}</div><p>早晚／環境 {day.nightTemp}</p></div><div className="rating"><b>LEVEL {day.level}</b><strong>{stars(day.level)}</strong><p>{day.weather}</p></div></header><p className="notice">{day.notice}</p><div className="lookgrid"><div><Photo src={day.maleImage} alt={`${day.chapter}男性穿搭`}/><h3>男生</h3><p>{day.maleOutfit}</p></div><div><Photo src={day.femaleImage} alt={`${day.chapter}女性穿搭`}/><h3>女生</h3><p>{day.femaleOutfit}</p></div></div><div className="essentials"><b>鞋款</b><span>{day.shoes}</span><b>要帶的外層</b><span>{day.outerLayer}</span></div><h3 className="routeTitle">今日精選行程</h3><div className="timeline">{day.itinerary.map((x,i)=><div className="stop" key={i}><time>{x.time}</time><div><b>{x.place}</b><p>{x.description}</p><small>{x.type} · {x.priority}</small></div></div>)}</div></article>}
